version: '2'

services:
  postgres:
    image: 'postgres:13'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 'postgres'

  site:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/blog-codify'
    volumes_from:
      - box
    stdin_open: true
    tty: true

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:
