default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
  password: postgres

development:
  <<: *default
  database: blog_codify_development

test:
  <<: *default
  database: blog_codify_test

production:
  <<: *default
  database: blog_codify_production
  username: blog_codify
  password: <%= ENV["BLOG_CODIFY_DATABASE_PASSWORD"] %>
